### ISSUE TITLE
missing dependencies for the following libraries: libz.so.1

### ISSUE THREAD

**Issue by jack338c** [ghostry/openwrt-gmod#5]
用LEDE源码编译时出错了，怎么解决？请指教

 /usr/bin/install -c ss-nat '/home/jack/source/build_dir/target-mips_24kc_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.5.6/ipkg-install/usr/bin'
 /bin/mkdir -p '/home/jack/source/build_dir/target-mips_24kc_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.5.6/ipkg-install/usr/include'
 /usr/bin/install -c -m 644 shadowsocks.h '/home/jack/source/build_dir/target-mips_24kc_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.5.6/ipkg-install/usr/include'
make[6]: Leaving directory '/home/jack/source/build_dir/target-mips_24kc_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.5.6/src'
make[5]: Leaving directory '/home/jack/source/build_dir/target-mips_24kc_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.5.6/src'
make[5]: Entering directory '/home/jack/source/build_dir/target-mips_24kc_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.5.6'
make[6]: Entering directory '/home/jack/source/build_dir/target-mips_24kc_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.5.6'
make[6]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/home/jack/source/build_dir/target-mips_24kc_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.5.6/ipkg-install/usr/lib/pkgconfig'
 /usr/bin/install -c -m 644 shadowsocks-libev.pc '/home/jack/source/build_dir/target-mips_24kc_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.5.6/ipkg-install/usr/lib/pkgconfig'
make[6]: Leaving directory '/home/jack/source/build_dir/target-mips_24kc_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.5.6'
make[5]: Leaving directory '/home/jack/source/build_dir/target-mips_24kc_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.5.6'
make[4]: Leaving directory '/home/jack/source/build_dir/target-mips_24kc_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.5.6'
touch /home/jack/source/build_dir/target-mips_24kc_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.5.6/.built
mkdir -p /home/jack/source/bin/targets/ar71xx/generic/packages /home/jack/source/build_dir/target-mips_24kc_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.5.6/ipkg-mips_24kc/shadowsocks-libev-spec/CONTROL /home/jack/source/staging_dir/target-mips_24kc_musl-1.1.15/pkginfo
install -d -m0755 /home/jack/source/build_dir/target-mips_24kc_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.5.6/ipkg-mips_24kc/shadowsocks-libev-spec/usr/bin
install -m0755 /home/jack/source/build_dir/target-mips_24kc_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.5.6/src/ss-{redir,tunnel} /home/jack/source/build_dir/target-mips_24kc_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.5.6/ipkg-mips_24kc/shadowsocks-libev-spec/usr/bin
install -m0755 ./files/shadowsocks.rule /home/jack/source/build_dir/target-mips_24kc_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.5.6/ipkg-mips_24kc/shadowsocks-libev-spec/usr/bin/ss-rules
install -d -m0755 /home/jack/source/build_dir/target-mips_24kc_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.5.6/ipkg-mips_24kc/shadowsocks-libev-spec/etc/config
install -m0644 ./files/shadowsocks.config /home/jack/source/build_dir/target-mips_24kc_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.5.6/ipkg-mips_24kc/shadowsocks-libev-spec/etc/config/shadowsocks
install -d -m0755 /home/jack/source/build_dir/target-mips_24kc_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.5.6/ipkg-mips_24kc/shadowsocks-libev-spec/etc/shadowsocks
install -m0600 ./files/shadowsocks.conf /home/jack/source/build_dir/target-mips_24kc_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.5.6/ipkg-mips_24kc/shadowsocks-libev-spec/etc/shadowsocks/config.json
install -m0600 ./files/shadowsocks.list /home/jack/source/build_dir/target-mips_24kc_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.5.6/ipkg-mips_24kc/shadowsocks-libev-spec/etc/shadowsocks/ignore.list
install -d -m0755 /home/jack/source/build_dir/target-mips_24kc_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.5.6/ipkg-mips_24kc/shadowsocks-libev-spec/etc/init.d
install -m0755 ./files/shadowsocks.spec /home/jack/source/build_dir/target-mips_24kc_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.5.6/ipkg-mips_24kc/shadowsocks-libev-spec/etc/init.d/shadowsocks
install -d -m0755 /home/jack/source/build_dir/target-mips_24kc_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.5.6/ipkg-mips_24kc/shadowsocks-libev-spec/usr/share/shadowsocks
install -m0644 ./files/shadowsocks.include /home/jack/source/build_dir/target-mips_24kc_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.5.6/ipkg-mips_24kc/shadowsocks-libev-spec/usr/share/shadowsocks/firewall.include
install -d -m0755 /home/jack/source/build_dir/target-mips_24kc_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.5.6/ipkg-mips_24kc/shadowsocks-libev-spec/etc/uci-defaults
install -m0755 ./files/shadowsocks.cron /home/jack/source/build_dir/target-mips_24kc_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.5.6/ipkg-mips_24kc/shadowsocks-libev-spec/etc/uci-defaults/shadowsocks-libev-spec
find /home/jack/source/build_dir/target-mips_24kc_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.5.6/ipkg-mips_24kc/shadowsocks-libev-spec -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
Package shadowsocks-libev-spec is missing dependencies for the following libraries:
libz.so.1
Makefile:120: recipe for target '/home/jack/source/bin/packages/mips_24kc/gmod/shadowsocks-libev-spec_2.5.6-135ceedb1404b8e8ce3edb2580a1027991e3e67c_mips_24kc.ipk' failed
make[3]: *** [/home/jack/source/bin/packages/mips_24kc/gmod/shadowsocks-libev-spec_2.5.6-135ceedb1404b8e8ce3edb2580a1027991e3e67c_mips_24kc.ipk] Error 1
make[3]: Leaving directory '/home/jack/source/feeds/gmod/package/shadowsocks'
package/Makefile:132: recipe for target 'package/feeds/gmod/shadowsocks/compile' failed
make[2]: *** [package/feeds/gmod/shadowsocks/compile] Error 2
make[2]: Leaving directory '/home/jack/source'
package/Makefile:128: recipe for target '/home/jack/source/staging_dir/target-mips_24kc_musl-1.1.15/stamp/.package_compile' failed
make[1]: *** [/home/jack/source/staging_dir/target-mips_24kc_musl-1.1.15/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/jack/source'
/home/jack/source/include/toplevel.mk:197: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by ghostry** [comment]
Package shadowsocks-libev-spec is missing dependencies for the following libraries:
libz.so.1
包2.6.8-libev规格缺少下列库的依赖关系： 
libz.so.1 

遇到错误翻译一下就知道了，然后去搜索。

**Comment by jack338c** [comment]
第一时间搜索了, 还是没解决我不是sdk, 也不是image builder编译，谢谢你

On Dec 18, 2016 1:55 PM, "ghostry" <notifications@github.com> wrote:

Package shadowsocks-libev-spec is missing dependencies for the following
libraries:
libz.so.1
包2.6.8-libev规格缺少下列库的依赖关系：
libz.so.1

遇到错误翻译一下就知道了，然后去搜索。

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ghostry/openwrt-gmod/issues/5#issuecomment-267805091>,
or mute the thread

**Comment by ergdfrte** [comment]
Add +zlib to this line: https://github.com/wongsyrone/lede-1/blob/master/package/external/shadowsocks-libev/Makefile#L46

I'm using mbedtls variant, so I didn't fix this issue in my repo, you can check shadowsocks/openwrt-shadowsocks@c4a4b35 for details.

**Comment by jack338c** [comment]
@uglee  thank you uglee!
